- name: conditions in Ansible
  hosts: localhost
  tasks:
  - name: identify the roboshop
    ansible.builtin.command: id roboshop
    register: output
    ignore_errors: True

  - name: print the command output
    ansible.builtin.debug:
      msg: "{{output}}"