- name: assigned the user in variable and dynamically check the user
  hosts: localhost
  vars:
    USER: Jyothi
  tasks:
  - name: print the user if exists if not create
    ansible.builtin.command: id Jyothi
    register: output
    ignore_errors: True

  - name: Check the user
    ansible.builtin.debug:
      msg: "User is:{{USER}}"
    when: USER=="Jyothi"
    ignore_errors: True

  - name: create the user
    become: yes
    ansible.builtin.user:
      name: Jyothi
    when: output.rc !=0

  - name: Print the user
    ansible.builtin.debug: 
      msg: "user is available"
    