- name: assigned the user in variable and dynamically check the user
  hosts: localhost
  vars:
    USER: Divya
  tasks:
  - name: print the user if exists if not create
    ansible.builtin.command: id bhanu
    register: output
    ignore_errors: True

  - name: Check the user
    ansible.builtin.debug:
      msg: "User is:{{USER}}"
    when: USER=="Divya"
    ignore_errors: True

  - name: create the user
    become: yes
    ansible.builtin.user:
      name: Divya
    when: output.rc !=0
    ansible.biltin.debug:
      msg: "Name {{USER}} is available"