- name: assigned the user in variable and dynamically check the user
  hosts: localhost
  vars:
    USER: bhanu
  tasks:
  - name: print the user if exists if not create
    ansible.builtin.command: id bhanu
    register: output
    ignore_errors: True

  - name: Check the user
    ansible.builtin.debug:
      msg: "User is:{{USER}}"
    when: NAME==bhanu