- name: advanced loops map
  hosts: localhost
  become: yes
  tasks:
  - name: install or remove the packages
    ansible.builtin.yum:
      name: "{{item.name}}"
      state: "{{item.state}}"
    loop:
    - {name:'nginx', state:'installed'}
    - {name:'postfix', state:'absent'}
    - {name:'mailx', state:'installed'}
